#ifndef __MAINPANEL_H
#define __MAINPANEL_H

void BuildMainPanelObjects ();
void SyncroMainpanel();	
void eventhandlermain (int oid, int val, double dval);


enum mainpanel {
	GEARLEVELUP = (MAIN_GROUP_OID * OBJECTS_PER_GROUP),
	GEARLEVERDOWN,
	L_GEAR_UNLK,
	C_GEAR_UNLK,
	R_GEAR_UNLK,
	L_GEAR_DOWN,
	C_GEAR_DOWN,
	R_GEAR_DOWN,
	L_GEAR_STAT,
	C_GEAR_STAT,
	FUEL_PUMPS,
	R_GEAR_STAT,
	AUTOBRAKE,
	BRAKELO,
	BRAKEMED,
	BRAKEMAX,
	BRAKELOOUT,
	BRAKEMEDOUT,
	BRAKEMAXOUT,
	ANTISKIDONOFF,
	ANTISKID,
	HOTBRAKE,
	BRAKEFAN,
	BRAKEFANHOT,
	BRAKEHOTON,
	BRAKELODECEL,
	BRAKEMEDDECEL,
	BRAKEMAXDECEL,
	BRAKELEFT_SERVO,
	BRAKERIGHT_SERVO,
	BRAKECENTER_SERVO,
	ACCUPRESS,
	BRAKEPCI1,
	BRAKEPCI2,
	BRAKEFAN_SWITCH,
	INT_LIGHTS,
	APUON2,
	AUTOBRAKE_DECEL,
	SPEED_GAUGE_SERVO,
	FS_SPEED_IAS,
	GEAR_STAT
};

#endif